[gus]
gus= true
ultradir = C:\ULTRASND


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off




[autoexec]
mount C -t dir "./" 
imgmount D -t iso -f iso "./anvil/Anvil.dat" 

cls 
ECHO OFF

C:
cd anvil
goto launcher


:launcher
cls 
ECHO  -----------------------------------------------------  
ECHO                      Anvil of Dawn 
ECHO  -----------------------------------------------------  
ECHO   1) Play Game        
ECHO   2) Play Game with Gravis Ultrasound
ECHO   3) Setup                          
ECHO  -----------------------------------------------------  
ECHO   4) Exit Program                             
ECHO  -----------------------------------------------------  
choice /c1234 /s Which program do you want to run? [1-4]: /n 
if errorlevel 4 goto exit
if errorlevel 3 goto setup
if errorlevel 2 goto gravis
if errorlevel 1 goto game


:game
cls
anvil
goto exit


:gravis
cls
GRAVIS.BAT
goto exit


:setup
cls
setup.exe
goto launcher


:exit
exit