[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[gus]
gus=true


[render]
viewport = fit
integer_scaling = off

[autoexec]
mount c -t dir "./"

C:

cd TheFanta

autotype -w 3 -p 3 f1 f2

PCDIZZY.EXE

exit