[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[autoexec]

mount C "~/Games/ROMs/dos/albion" -t dir
imgmount D "~/Games/ROMs/dos/albion/game.ins" -t iso

cls 
ECHO OFF
goto launcher

:launcher
cls 
ECHO  -------------------------------------------  
ECHO                     Albion  
ECHO  -------------------------------------------  
ECHO   1) Play        
ECHO   2) Setup                                   
ECHO  -------------------------------------------  
ECHO   3) Exit program                             
ECHO  -------------------------------------------  

choice /c123 /s Which program do you want to run? [1-3]: /n 
if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto game


:game
cls
C:
ALBILOW.BAT
goto exit


:setup
cls
C:
setup.exe
goto launcher


:exit
exit