[cpu]
cpu_cycles = 5000
cpu_cycles_protected = auto
cputype = 386
cpu_throttle = on

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[dosbox]
machine=svga_paradise
memsize=32

[render]
viewport = fit
integer_scaling = off

[autoexec]
mount C "./" -t dir

c:
cls
cd wland
run
exit