[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]
mount C "./twnoname" -t dir
imgmount D "./twnoname/cd/Town with no name.cue" -t cdrom

mixer sb 30
c:
ECHO OFF
cd twnoname
cls
call town
exit