[midi]
mididevice = mt32

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x

[autoexec]
imgmount D  -t cdrom "./game.gog"
mount C -t dir "./" 

c:

RAMPAGE.EXE

exit