[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]

mount C "~/Games/ROMs/dos/all-new-worlds-of-lemmings.conf/lemm3/" -t dir
imgmount D "~/Games/ROMs/dos/all-new-worlds-of-lemmings.conf/lemm3/cd/LEMMINGS3.CUE" -t cdrom

C:
cls
cd l3
call l3

exit