[midi]
mididevice = mt32

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C -t dir "./" 
imgmount D -t cdrom "./" 

cls 

ECHO OFF

SET ARENADATA=C:

d:

ACD -Ssbpdig.adv -IOS220 -IRQS7 -DMAS1 -Mgenmidi.adv -IOM330 -IRQM2 -DMAM1

exit
