[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[dosbox]
machine	= svga_s3
memsize	= 63
vmemsize = 1

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]

mount C -t dir "./" 
mount D -t cdrom "./CD1" 


c:
cls
ECHO OFF
goto launcher




:launcher
ECHO  ------------------------------------------
ECHO            Wing Commander IV
ECHO  ------------------------------------------
ECHO   1) Wing Commander IV: The Price of Freedom
ECHO   2) Game settings
ECHO  ------------------------------------------
ECHO   3) Exit
ECHO  ------------------------------------------

@choice /c123 /s Choose option [1-3]: /n

if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto play


:play
cls
C: 
cd wc4
wc4.exe
goto exit



:setup 
cls
C:
cd WC4 
wc4.exe -i
goto launcher


:exit
exit