[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[dosbox]
machine	= svga_s3
memsize	= 63
vmemsize = 1

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]

mount C -t dir "./WC4PoF" 
imgmount d -t cdrom "./WC4PoF/CD/cd1.iso" "./WC4PoF/CD/cd2.iso" "./WC4PoF/CD/cd3.iso" "./WC4PoF/CD/cd4.iso" "./WC4PoF/CD/cd5.iso" "./WC4PoF/CD/cd6.iso" 
c:
cd wc4
echo off
cls
echo.
echo Press CTRL-F4 to change CD's when prompted. There are 6 CD's in total.
echo.
pause
cls
@WC4
exit