[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off

[gus]
gus=true

[autoexec]
mount c -t dir "./Bureau13"
imgmount D -t cdrom "./Bureau13/cd/B13.CUE" 

ECHO OFF

c:
cd b13
cls
call run
exit