[gus]
gus      = true
ultradir = C:\ULTRASND
gusbase  = 220
gusirq   = 11
gusdma   = 1

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]

mount C -t dir "./BLacktho" 
imgmount D  -t cdrom "./BLacktho/cd/BlackThorne.iso"

cls

C:
cd BTHORNE
run
exit