[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[gus]
gus=true


[render]
viewport = fit
integer_scaling = off

[autoexec]
mount c -t dir "./"
imgmount d -t cdrom  "./ddumps/cd/down-in-the-dumps_cd1.ISO" "./ddumps/cd/down-in-the-dumps_cd2.ISO" "./ddumps/cd/down-in-the-dumps_cd3.ISO" 
c:
cls
echo.
echo This game spans 3 CDs. Press Ctrl+F4 when prompted to switch to the next disc.
echo.
pause
cls
cd ddumps
call playdid
exit