[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
aspect = stretch
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = pentium

[sblaster]
sbtype = sb16

[gus]
gus = true

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir "~/Games/ROMs/windows3x/titanic_adventure_out_of_time.conf/drives/c" 
imgmount D -t iso "~/Games/ROMs/windows3x/titanic_adventure_out_of_time.conf/drives/d/Titanic1.cue"
imgmount E -t iso "~/Games/ROMs/windows3x/titanic_adventure_out_of_time.conf/drives/d/Titanic2.cue"


SET PATH=%PATH%;C:\WINDOWS;C:\DOS;Y:\DOS
SET TEMP=C:\WINDOWS\TEMP

ECHO OFF

goto launcher

:launcher
cls 
ECHO  -------------------------------------------  
ECHO         Titanic Adveture Out of Time
ECHO  -------------------------------------------  
ECHO   1) Play        
ECHO   2) Install Game                                
ECHO  -------------------------------------------  
ECHO   3) Exit                              
ECHO  -------------------------------------------  
choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit         
if errorlevel 2 goto setup
if errorlevel 1 goto game


:game
cls
C:
win c:\titanic\titanic
goto launcher


:setup
cls
C:
win  D:\setup
goto launcher


:exit
exit