[midi]
mididevice = mt32


[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off

[autoexec]
mount c -t dir "./MagColl"
mount a -t floppy "./MagColl/floppy" 
c:
cd mag
cls
call COLLECT1
exit