[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[mouse]
mouse_capture = onstart   
mouse_middle_release=true   
mouse_sensitivity= 50


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x


[autoexec]
mount C  -t dir "./callahan/"
imgmount d -t cdrom "./callahan/cd\CALLAHAN.cue"

ECHO OFF 

c:
cd ccs
cls
call run
exit