[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]
mount C "./" -t dir
mount a -t cdrom "./transyl3" 

c:
ECHO OFF
cls
echo.
echo Press ENTER to enable graphics once the game has started.
echo.
pause
cd transyl3
call novel
exit