[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]

mount C -t dir"./" 
imgmount D -t iso -fs iso "./game.ins" 

D:
b.exe

exit