[midi]
mididevice = mt32

[cpu]
cpu_cycles = 3000
cpu_cycles_protected = auto
cputype = 386
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C "./" -t dir

C:

cd BAT

BAT

exit