[dosbox]
machine=svga_s3
memsize=63

[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[mouse]
mouse_capture = onstart   
mouse_middle_release=true   
mouse_sensitivity= 50

[mixer]
prebuffer=20


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x


[autoexec]

mount c "./timegate"

c:
cls
echo off
cls
echo.
echo Press 1 for Time Gate: Knight's Chase w/ SoundBlaster
echo Press 2 for Time Gate: Knight's Chase w/ MT-32
echo Press 3 for Time Gate: Knight's Chase SVGA w/ SoundBlaster
echo Press 4 for Time Gate: Knight's Chase SVGA w/ Sound Canvas
echo Press 5 to Quit
echo.
choice /C:12345 /N Please Choose:

if errorlevel = 5 goto quit
if errorlevel = 4 goto SVGASC
if errorlevel = 3 goto SVGASB
if errorlevel = 2 goto MT32
if errorlevel = 1 goto SB16

:SB16
imgmount d ".\timegate\cd\Time Gate - Knight's Chase.cue" -t cdrom
CONFIG -set "mididevice=default"
cd TIMEGATE
copy .\sb16\*.* .\
cls
@TIMEGATE
goto quit

:MT32
imgmount d ".\timegate\cd\Time Gate - Knight's Chase.cue" -t cdrom
CONFIG -set "mididevice=mt32"
CD TIMEGATE
copy .\mt32\*.* .\
cls
@TIMEGATE
goto quit

:SVGASB
imgmount d ".\timegate\cd\Time_Gate_Knight's_Chase_DOS-Win_Eng-SVGA.iso" -t cdrom
CONFIG -set "mididevice=default"
CD KNIGHTS
CD SVGA
copy .\sb16\*.* .\
cls
@KNIGHTS
goto quit

:SVGASC
imgmount d ".\timegate\cd\Time_Gate_Knight's_Chase_DOS-Win_Eng-SVGA.iso" -t cdrom
CONFIG -set "mididevice=fluidsynth"
CD KNIGHTS
CD SVGA
copy .\sc55\*.* .\
cls
@KNIGHTS
goto quit

:quit
exit