[cpu]
cpu_cycles = 3000
cpu_cycles_protected = auto
cputype = 386
cpu_throttle = on

[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
glshader=sharp


[autoexec]
mount C "./" -t dir
C:
JOURNEY
exit