[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = 486

[sblaster]
sbtype = sb16

[gus]
gus = false

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir "./Congo-Th" 
imgmount D -t iso "./Congo-Th/cd/CD1.cue"

d: 
path=C:\;z:\;c:\windows\  
cls 
win runexit congo
exit