[dosbox]
machine=svga_s3
memsize=63

[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x


[autoexec]

mount C "./" -t dir
imgmount D -t cdrom  "./cd/Synnergist.img"

C:

SYNN

cd 21STCENT/SYN

exit