[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[midi]
mididevice = mt32


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C  -t dir "./"
ingmount D "./cd/CD1" -label DISK1 -t cdrom
imgmount E "./cd/CD2" -label DISK2 -t cdrom
imgmount F "./cd/CD3" -label DISK3 -t cdrom
imgmount G "./cd/CD4" -label DISK4 -t cdrom

c:
cls 
ECHO OFF
goto launcher


:launcher
cls 
ECHO  -------------------------------------------  
ECHO      Tex Murphy - Under a Killing Moon
ECHO  -------------------------------------------  
ECHO   1) Play               
ECHO   2) Install  
ECHO  -------------------------------------------  
ECHO   3) exit program                             
ECHO  -------------------------------------------  

choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto install               
if errorlevel 1 goto game


:game
cls
C:
cd moon
tex3
goto launcher



:install
cls
D:
install
goto launcher


:exit
exit