[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C  -t dir "./"
imgmount D -t cdrom  "./cd/CD1.iso"  
imgmount E -t cdrom  "./cd/CD2.iso" 
imgmount F -t cdrom  "./cd/CD3.iso"  
imgmount G -t cdrom  "./cd/CD4.iso" 

c:
cls
ECHO OFF
goto launcher


:launcher

ECHO  -------------------------------------------  
ECHO      Tex Murphy - Under a Killing Moon
ECHO  -------------------------------------------  
ECHO   1) Play               
ECHO   2) Install  
ECHO  -------------------------------------------  
ECHO   3) exit program                             
ECHO  -------------------------------------------  

choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto install               
if errorlevel 1 goto game


:game
cls
C:
cd moon
tex3
goto launcher



:install
cls
D:
install
goto launcher


:exit
