[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[gus]
gus = true

[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
imgmount D -t cdrom "./afraid/cd/Are You Afraid of the Dark - The Tale of Orpheo's Curse (1994)(Viacom New Media).iso" 
mount C -t dir "./afraid" 

ECHO OFF

cls

C:

cd VNM

cd AFRAID

AFRAID

exit'
afraid