[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]

mount C -t dir "./"
imgmount D "./game.gog" -t iso -fs iso

D:
@ECHO OFF
goto launcher

:launcher
cls
ECHO  --------------------------------------- 
ECHO  Ultima Underworld - Labyrinth of Worlds           
ECHO  --------------------------------------- 
ECHO   1) Play game    
ECHO   2) Game settings     
ECHO   3) Exit program               
ECHO  ------------------------------------ 

choice /c123 /s Choose language: [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto run


:run
cls
uw2.bat
goto exit


:setup
cls
install2.exe
goto launcher


:exit
exit