[dosbox]
title=Windows 95
memsize=64

[video]
vmemsize=8
vesa modelist width limit=0
vesa modelist height limit=0

[sdl]
fullscreen=true

[dos]
# Set 'ver=7.1' if using Win95 OSR2 (95B) or later
ver=7.1
hard drive data rate limit=0
floppy drive data rate limit=0

[cpu]
cputype=pentium_mmx
core=normal

[sblaster]
sbtype=sb16vibra

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakeio=true
int13fakev86io=true

[ide, secondary]
int13fakeio=true
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none

[ethernet, pcap]
realnic=list

[autoexec]
@echo off
imgmount C -t hdd "./hdd_Win95.img"
IMGMOUNT D -t iso "./China.iso"

ECHO OFF
cls
ECHO Shortcut F12+Esc to display menu.
ECHO Shortcut F12+D Swap between mounted CD images.
ECHO Shortcut Ctrl+F9 Exit DOSBox-X.
ECHO Shortcut Ctrl+F10 Capture the mouse.
pause
boot -l c