[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[dosbox]
machine=svga_s3
memsize=64

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]
@mount c "./XCOMUF"
imgmount d "./XCOMUF/cd/UFO Enemy Unknown.iso" -t cdrom

c:
cls
cd ufo
call run
exit