[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
[midi]
mididevice = fluidsynth


[gus]
gus = true
ultradir = C:\ULTRASND


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[render]
aspect=true
scaler=normal2x


[autoexec]
mount c "./pandora"
imgmount e "./pandora/cd/PANDORA1.iso" -t cdrom
imgmount f "./pandora/cd/PANDORA2.iso" -t cdrom
imgmount g "./pandora/cd/PANDORA3.iso" -t cdrom
imgmount h "./pandora/cd/PANDORA4.iso" -t cdrom
imgmount i "./pandora/cd/PANDORA5.iso" -t cdrom
imgmount j "./pandora/cd/PANDORA6.iso" -t cdrom

c:
cd pandora
cls
call run
exit