[midi]
mididevice = mt32

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C -t dir "./" 
imgmount D -t iso -fs fat "./EWJ2.inst" 

         
C: 
CD EWJ
cls 
ECHO OFF
goto launcher

:launcher
cls 
ECHO  -------------------------------------------  
ECHO   Earhworm Jim 2 Launcher  
ECHO  -------------------------------------------  
ECHO   1) Earthworm Jim 2       
ECHO   2) Setup  
ECHO   3) Exit                             
ECHO  -------------------------------------------  

choice /c123 /s Which program do you want to run? [1-3]: /n 
if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto game


:game
cls
EWJ2.exe
goto exit


:setup
cls
SETUP.exe
goto launcher


:exit
exit