[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off



[autoexec]
mount c -t dir "./"

ECHO OFF

c:
cls
echo.
echo Note: If you have Buck Rogers: Countdown to Doom installed you may
echo transfer savegame files or characters not currently in a party into
echo Matrix Cubed via the game interface.
echo.
pause
cd BRmatrix
@call start
exit