[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[gus]
gus=true


[render]
viewport = fit
integer_scaling = off

[autoexec]
mount c -t dir "./"
imgmount d -t cdrom  "./evidence/cd/EVIDENCE.iso" 

c:
cls
cd evidence
call evidence
exit
