[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = 486

[sblaster]
sbtype = sb16

[gus]
gus = false

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir "./Frankens" 
imgmount D -t iso "./Frankens/cd/cd.cue"

SET PATH=%PATH%;C:\WINDOWS;C:\DOS;Y:\DOS;C:\
SET TEMP=C:\WINDOWS\TEMP

C: 
cd intrplay\frankie
cls 
win runexit frankie
exit