[midi]
mididevice = mt32

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C "./" -t dir
imgmount d "./homm2.gog" -t iso

C: 
cls 
ECHO OFF
goto launcher

:launcher
cls 
ECHO  -------------------------------------------  
ECHO   Heroes of Might and Magic II GOLD Launcher  
ECHO  -------------------------------------------  
ECHO   1) Heroes of Might and Magic II GOLD        
ECHO   2) Map Editor                               
ECHO  -------------------------------------------  
ECHO   3) Game DOS Settings                        
ECHO   4) Music Tracks Selector                    
ECHO  -------------------------------------------  
ECHO   5) Exit program                             
ECHO  -------------------------------------------  
choice /c12345 /s Which program do you want to run? [1-5]: /n 

if errorlevel 5 goto exit
if errorlevel 4 goto music
if errorlevel 3 goto setup
if errorlevel 2 goto editor
if errorlevel 1 goto game


:game
cls
heroes2.exe
goto exit

:editor
cls
EDITOR2.EXE
goto exit


:setup
cls
install.exe
goto launcher


:music
cls
ECHO  ------------------------------------------- 
ECHO            HoMM II Track Selector                      
ECHO  ------------------------------------------- 
ECHO   1) Succession Wars music tracks            
ECHO   2) Price of Loyalty music tracks           
ECHO  ------------------------------------------- 
ECHO   3) Leave without change                    
ECHO  ------------------------------------------- 
CHOICE /c123 /s Which town tracks do you want to use in-game? [1-3]: /n 
IF errorlevel 3 goto launcher
IF errorlevel 2 goto pol
IF errorlevel 1 goto sw


:sw

mount -u D
mount D "./" -t dir

cls
COPY D:\music\sw\*.* D:\music\*.*
ECHO .
ECHO The game will now use Succession Wars tracks for town music.
pause
mount -u D
imgmount D "./homm2.ins" -t iso -fs iso

cls
goto launcher


:pol
cls
mount -u D

mount D "./" -t dir

COPY D:\music\pol\*.* D:\music\*.*

cls
ECHO .
ECHO The game will now use Price of Loyalty tracks for town music.
pause
mount -u D

imgmount D "./homm2.ins" -t iso -fs iso
cls
goto launcher

:exit
exit
