[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C "./" -t dir

C: 
cls 
ECHO OFF
goto launcher

:launcher
cls 
ECHO  -------------------------------------------  
ECHO        Legends of Murder Collection
ECHO  -------------------------------------------  
ECHO   1) Play Stonedale Castle     
ECHO   2) Play Grey Haven  
ECHO  -------------------------------------------  
ECHO   3) Exit Program                             
ECHO  -------------------------------------------  
choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto game2
if errorlevel 1 goto game1


:game1
cls
c:
cd LoM1
STONEDAL.exe
goto launcher


:game2
cls
C:
cd LoM2
GREYHAVE.exe
goto launcher


:exit
exit