[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
aspect = stretch
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = pentium

[sblaster]
sbtype = sb16

[gus]
gus = true

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir "~/Games/ROMs/windows3x/titanic-adventure-out-of-time.conf/drives/c" 
imgmount D -t iso "~/Games/ROMs/windows3x/titanic-adventure-out-of-time.conf/drives/d/Titanic1.cue"
imgmount E -t iso "~/Games/ROMs/windows3x/titanic-adventure-out-of-time.conf/drives/d/Titanic2.cue"


SET PATH=%PATH%;C:\WINDOWS;C:\DOS;Y:\DOS
SET TEMP=C:\WINDOWS\TEMP
ECHO OFF

C:
win  D:\setup
exit