[midi]
mididevice = mt32

[gus]
gus      = true
ultradir = C:\ULTRASND
gusbase  = 220
gusirq   = 11
gusdma   = 1

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C -t dir "./" 
imgmount D -t iso -fs iso "./HARVEST.DAT" "./HARVEST3.DAT" "./HARVEST4.DAT"

cls 
ECHO OFF
goto launcher

:launcher
cls 
ECHO This game spans 3 discs.  Press ctrl-F4 to switch when prompted.
ECHO  -------------------------------------------  
ECHO                Harvester
ECHO  -------------------------------------------  
ECHO   1) Play        
ECHO   2) Setup    
ECHO  -------------------------------------------  
ECHO   3) Exit Program                             
ECHO  -------------------------------------------  
choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto game


:game
cls
c:
harvest.exe
goto exit


:setup
cls
c:
setsound.bat
goto launcher


:exit
exit
