[sdl]
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[autoexec]
mount C "$GAMEDIR/" -t dir
imgmount D "$GAMEDIR/cd/Lemmings 3D.cue" -t cdrom

C:
run
exit