[mouse]
mouse_capture = onstart   
mouse_middle_release=true   
mouse_sensitivity= 90

[sdl]
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[autoexec]
mount C -t dir "./Lemmings 3D (1995)" 
imgmount D -t cdrom "./Lemmings 3D (1995)/CD/Lemmings 3D.cue" 

C:
RUN
exit