[midi]
mididevice = mt32

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off


[autoexec]
mount C -t dir "./" 

C:
@echo off
cls

ECHO Duke Nukem Pack---------------------------
ECHO ------------------------------------------
ECHO 1) Duke Nukem Ep.1: Sharpnel City
ECHO 2) Duke Nukem Ep.2: Mission: Moonbase
ECHO 3) Duke Nukem Ep.3: Trapped in the Future
ECHO 4) Duke Nukem 2
ECHO ------------------------------------------
ECHO 5) exit program
ECHO ------------------------------------------

choice /c1234 /s Which game do you want to run? [1-5]: /n 

if errorlevel 5 goto exit
if errorlevel 4 goto n2
if errorlevel 3 goto e3
if errorlevel 2 goto e2
if errorlevel 1 goto e1

:e1
dn1.exe
exit

:e2
dn2.exe
exit

:e3
dn3.exe
exit

:n2
cls
nukem2.exe
exit


:exit
exit