[midi]
mididevice = mt32

[gus]
gus= true
ultradir = C:\ULTRASND


[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[autoexec]
mount C "./" -t dir

cls 
ECHO OFF

C:
cd battle
chess.EXE
exit