[midi]
mididevice = mt32

[gus]
gus= true
ultradir = C:\ULTRASND


[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[autoexec]
mount C "./" -t dir

cls 
ECHO OFF
goto launcher

:launcher
cls 

ECHO  -------------------------------------------  
ECHO               Chinese Chess 
ECHO  -------------------------------------------  
ECHO   1) Play Chinese Chess                                          
ECHO   2) Setup Chinese Chess   
ECHO  -------------------------------------------  
ECHO   3) Exit Program                             
ECHO  -------------------------------------------  
choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto setupchinese
if errorlevel 1 goto chinese


:chinese
cls
C:
cd Chinese
CHESSII.EXE
goto exit


:setupchinese
cls
C:
cd Chinese
setup
goto launcher


:exit
exit