[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect = stretch
viewport = fit
integer_scaling = off

[autoexec]
mount D "~/Games/ROMs/dos/abuse.conf/Abuse/Abuse" -t cdrom
mount C "~/Games/ROMs/dos/abuse.conf/Abuse/cd" -t dir

C:
run
exit