[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on

[midi]
mididevice = mt32

[sdl]
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]
mount C "./" -t dir
imgmount D "./GAME.DAT" -t cdrom


C:
cls 
ECHO OFF
goto launcher


:launcher
cls 
ECHO  -------------------------------------------  
ECHO               Time Commando
ECHO  -------------------------------------------  
ECHO   1) Play        
ECHO   2) Set Sound                                   
ECHO  -------------------------------------------  
ECHO   3) exit program                             
ECHO  -------------------------------------------  

choice /c123 /s Which program do you want to run? [1-3]: /n 

if errorlevel 3 goto exit
if errorlevel 2 goto setup
if errorlevel 1 goto game


:game
cls
C:
TIMECO.EXE
goto exit


:setup
cls
C:
setsound
goto launcher


:exit
exit