[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = 486

[sblaster]
sbtype = sb16

[gus]
gus = false

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir  "./BlueHeat/" 
imgmount D -t iso "./BlueHeat/cd/cd1.iso"  "./BlueHeat/cd/cd2.iso" "./BlueHeat/cd/cd3.iso" "./BlueHeat/cd/cd4.iso"  

SET PATH=%PATH%;C:\WINDOWS;C:\DOS;Y:\DOS;
SET TEMP=C:\WINDOWS\TEMP

cls
C:
cd BlueHeat 
cls
echo.
echo This game spans 4 discs.  Press ctrl-F4 to switch when prompted.
echo.
pause 
cls
win c:\runexit.exe c:\blheat\BLHEAT16.EXE
pause 