[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x

[gus]
gus=true

[autoexec]
mount C  -t dir "./chewy/"
imgmount d -t cdrom "./chewy/cd/chewy.cue"

ECHO OFF 

c:
cls
cd CHEWY_F5
chewy
exit