[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off

[autoexec]

mount C -t dir "./" 
imgmount D  -t cdrom "./game.iso"

C:

bstone

exit
