[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
viewport = fit
integer_scaling = off

[autoexec]
mount c -t dir "./DesStr"
imgmount d -t cdrom "./DesStr/cd/Jungle_Desert_Strike.cue" 
c:
cls
cd desert
call run
exit