[midi]
mididevice = mt32


[cpu]
cpu_cycles = 25000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[sdl]
fullscreen=true
output=opengl


[render]
viewport = fit
integer_scaling = off


[autoexec]
mount c -t dir "./" -freesize 99999
imgmount d -t cdrom "./construc/cd/CONSTRUCTR1.iso" 
c:
cls
cd construc
call run.bat
exit