[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = pentium

[midi]
mpu401     = intelligent
mididevice = fluidsynth

[sblaster] 
sbtype=sb16 


[autoexec]
mount D -t cdrom "~/Games/ROMs/windows3x/bermuda-syndrome.conf/BermudaS/"
mount C    -t dir   "~/Games/ROMs/windows3x/bermuda-syndrome.conf/BermudaS/" 


C: 

SET PATH=%PATH%;C:\WINDOWS;Y:\DOS;C:\DOS;
SET TEMP=C:\WINDOWS\TEMP

CLS 

WIN C:\RUNEXIT.exe bermuda
EXIT 

