[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = pentium

[midi]
mpu401     = intelligent
mididevice = fluidsynth

[sblaster] 
sbtype=sb16 



[autoexec]
imgmount D -t cdrom "~/Games/ROMs/windows3x/ace-ventura.conf/AceVentu/cd/CD.iso"
mount C    -t dir   "~/Games/ROMs/windows3x/ace-ventura.conf/AceVentu/" 


C: 

SET PATH=%PATH%;C:\WINDOWS;Y:\DOS;C:\DOS;C:\7thlevel\ace\;D:\ace\
SET TEMP=C:\WINDOWS\TEMP

CD C:\7thLEVEL\ACE

CLS 

WIN C:\RUNEXIT.exe C:\7THLEVEL\ACE\ACE.EXE D:\ACE\ace.bin   

EXIT 