[dosbox]
machine  = svga_s3
vmemsize = 4

[sdl]
fullscreen = on
pause_when_inactive = yes

[render]
viewport = fit
integer_scaling = off

[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cpu_throttle = on
cputype = 486

[sblaster]
sbtype = sb16

[gus]
gus = false

[midi]
mpu401     = intelligent
mididevice = fluidsynth


[autoexec]
mount C -t dir "./MummyToP" 
imgmount D -t iso "./nemesisw/cd/Nemesis CD1.cue"  "./nemesisw/cd/Nemesis CD2.cue"   "./nemesisw/cd/Nemesis CD3.cue"   "./nemesisw/cd/Nemesis CD4.cue"   "./nemesisw/cd/Nemesis CD5.cue" 

ECHO OFF
c:
cls
echo.
echo This game is composed of 5 cd's.
echo.
echo To switch cd's press Ctrl+F4.
echo.
pause
cls
cd nemesisw
@call run
exit