[midi]
mididevice = mt32


[cpu]
cpu_cycles = 50000
cpu_cycles_protected = auto
cputype = 486
cpu_throttle = on


[mouse]
mouse_capture = onstart   
mouse_middle_release=true   
mouse_sensitivity= 50

[gus]
gus=true

[sdl]   
fullresolution=desktop
windowresolution=original
fullscreen=true
output=opengl

[render]
aspect=true
scaler=normal2x


[autoexec]
mount C -t dir "./JCATF" 

cls
C:

:menu
@echo off
cls
echo.
echo Press 1 to play Advanced Tactical Fighters
echo Press 2 to play NATO Fighters (Expansion Disk)
echo Press 3 to play ATF Network Multiplayer
echo Press 4 to play NATO Network Multiplayer
echo Press 5 to Quit
echo.
echo 2 CD's are currently mounted.  The first is the original Janes ATF and
echo the second is for the NATO fighters expansion.  Press ctrl-F4 in game
echo to switch between discs if needed
echo.
echo Network Note: Both players must choose either ATF or NATO. They can not
echo connect to eachother.
echo.
choice /C:12345 /N Please Choose:

if errorlevel = 5 goto quit
if errorlevel = 4 goto network_nato
if errorlevel = 3 goto network_atf
if errorlevel = 2 goto NATO
if errorlevel = 1 goto ATF

:ATF
imgmount d ./JCATF/cd/ATF_1_03F.iso ./JCATF/cd/NATO_1_00F.img -t cdrom
cd janes
cd atf
cls
@call ATF
goto quit

:NATO
imgmount d ./JCATF/NATO_1_00F.img ./JCATF/ATF_1_03F.iso -t cdrom
cd janes
cd atf
cls
@call NATO
goto quit

:network_atf
imgmount d ./JCATF/ATF_1_03F.iso ./JCATF/NATO_1_00F.img -t cdrom
cls
net_atf

:network_nato
imgmount d ./JCATF/NATO_1_00F.img ./JCATF/ATF_1_03F.iso -t cdrom
cls
net_n

:quit
exit